name: LINT-TEST-BUILD-CHECK

on:
  push:
     branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          pip install -r requirements.txt
          pylint server/application.py
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          pip install  -r requirements.txt
          pytest --junixtxml=junit/test-results.xml

  build-test:
    needs: [lint, unit-tests]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t test-image ./server --file ./server/dockerfile
      - name: Run Docker container
        run: docker run -d --name app-server8000 -p 8000:8000 --restart unless-stopped test-image
      - name: Wait for service to start
        run: sleep 11
      - name: List running containers
        run: docker ps -a
      - name: Wait a bit more
        run: sleep 11
      - name: Integration test: curl service
        run: '127.0.0.1:8000'

